### ISSUE TITLE
notebook does not work as expected

### ISSUE THREAD

**Issue by yuvalkirstain** [QianWangX/InstructEdit#2]
Hi, running your notebook and looking at the output image looks like this:

<img width="420" alt="image" src="https://github.com/QianWangX/InstructEdit/assets/57996478/d4902421-2873-4203-89ba-70d0bac9bf7b">

might be a bug in your code. please update the notebook.

**Comment by QianWangX** [comment]
Thank you yuvalkirstain, I think that's because I set the default parameter `is_blip2_description=False`. For this cat and dog example, BLIP2 description is important to get a good result. I already updated the notebook and you can try the new one. For other images, you can try both True or False to see the difference.
