### ISSUE TITLE
Other images didn't work

### ISSUE THREAD

**Issue by Leanwithming** [QianWangX/InstructEdit#8]
I have tried other images, and I find that it has a correct mask, but the object remains the same. For example, My insturction is "Change the Stop sign to Parking sign."
![Traffic_sign_mask](https://github.com/QianWangX/InstructEdit/assets/116648807/4221eed2-d71f-447e-8514-e4c590cb7df5)
![Traffic_sign](https://github.com/QianWangX/InstructEdit/assets/116648807/b689b0b9-d123-4c21-8708-9db086a6bc80)

**Comment by QianWangX** [comment]
Hi @Leanwithming , did you try to tune the parameter `encoding_ratio`? You can try to make it larger such as 0.9 to see if you can modify it. If still not working, I think it may because the stable diffusion backbone in the codebase has some difficulties identifying the text. The stable diffusion itself is not trained on images which contains high quality texts. It generally works better when you generate or edit image without text.

**Comment by Leanwithming** [comment]
> Hi @Leanwithming , did you try to tune the parameter `encoding_ratio`? You can try to make it larger such as 0.9 to see if you can modify it. If still not working, I think it may because the stable diffusion backbone in the codebase has some difficulties identifying the text. The stable diffusion itself is not trained on images which contains high quality texts. It generally works better when you generate or edit image without text.

Thanks for replying! and May I ask if you have used InstructEdit to do experiments on some popular/common dataset?

**Comment by QianWangX** [comment]
Hi @Leanwithming , sorry I didn't see your reply. I didn't try InstructEdit on some other datasets by myself. But if you have done so, feel free to share what are the results :)
